### ISSUE TITLE
[Bug]: Cluster Operator reconciles the Kafka resource in a tight loop after upgrade to 1.2.0

### ISSUE THREAD

**Issue by mhorcajada** [strimzi/strimzi-kafka-operator#13079]
### Bug Description

After upgrading the Cluster Operator from 1.1.0 to 1.2.0, one of my Kafka clusters gets reconciled continuously, roughly once per second, without anything actually changing in the cluster. The operator sits at 550-800m CPU permanently as a result. Before the upgrade, on 1.1.0, the same cluster reconciled on the normal periodic interval and the operator idled at a few m of CPU.

The cluster itself is healthy the whole time (`Ready=True`, data keeps flowing through the connectors), so this is not a functional outage. It is the operator burning CPU in a self-triggered reconciliation loop.

I spent a while narrowing this down and I think I have it isolated to a single field, so I will lay out what I found.

## What triggers the loop

The only thing that changes between two consecutive reconciliations is `lastTransitionTime` on the `Ready` condition of the Kafka resource. The condition status stays `True` the entire time. Every reconciliation rewrites that timestamp, the status write is seen by the watch as a MODIFIED event, and that event triggers the next reconciliation, which rewrites the timestamp again.

Two snapshots of `.status` three seconds apart, nothing else changes:

```
$ kubectl get kafka kafka-cluster -n kafka -o json | jq '.status' > /tmp/s1.json
$ sleep 3
$ kubectl get kafka kafka-cluster -n kafka -o json | jq '.status' > /tmp/s2.json
$ diff /tmp/s1.json /tmp/s2.json
5c5
<       "lastTransitionTime": "2026-08-21T01:09:33.993113162Z",
---
>       "lastTransitionTime": "2026-08-21T01:09:36.900166883Z",
```

The condition it belongs to is `Ready=True`:

```
$ kubectl get kafka kafka-cluster -n kafka -o jsonpath='{range .status.conditions[*]}{.type}={.status} reason={.reason} lastTransition={.lastTransitionTime}{"\n"}{end}'
Ready=True reason= lastTransition=2026-08-20T19:14:57.196348289Z
```

As far as I understand the convention, `lastTransitionTime` should only move when the condition actually transitions to a new status. Here the status never leaves `True`, but the timestamp is regenerated on every pass, so it looks like the condition is being rebuilt from scratch each reconciliation instead of the previous timestamp being carried over when the status is unchanged.

## It is triggered by the watch, not the timer

With the operator log at INFO, the loop is visible and every reconciliation is a `(watch)` reconciliation, not a `(timer)` one. The pattern repeats without pause:

```
2026-08-20 19:28:49 INFO  AbstractOperator:242 - Reconciliation #1359(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster will be checked for creation or modification
2026-08-20 19:28:50 INFO  CrdOperator:147 - Reconciliation #1359(watch) Kafka(kafka/kafka-cluster): Status of Kafka kafka-cluster in namespace kafka has been updated
2026-08-20 19:28:50 INFO  AbstractOperator:521 - Reconciliation #1359(watch) Kafka(kafka/kafka-cluster): reconciled
2026-08-20 19:28:50 INFO  AbstractOperator:498 - Reconciliation #1361(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster in namespace kafka was MODIFIED
2026-08-20 19:28:50 INFO  AbstractOperator:242 - Reconciliation #1360(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster will be checked for creation or modification
2026-08-20 19:28:51 INFO  CrdOperator:147 - Reconciliation #1360(watch) Kafka(kafka/kafka-cluster): Status of Kafka kafka-cluster in namespace kafka has been updated
2026-08-20 19:28:51 INFO  AbstractOperator:498 - Reconciliation #1362(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster in namespace kafka was MODIFIED
2026-08-20 19:28:51 INFO  AbstractOperator:521 - Reconciliation #1360(watch) Kafka(kafka/kafka-cluster): reconciled
```

You can read the cycle straight off those lines: `Status ... has been updated` is immediately followed by `... was MODIFIED`, which kicks off the next `(watch)` reconciliation, which updates the status again. The reconciliation numbers keep climbing one after another with no gap.

The reconciliation counter confirms the rate. Two reads of the Prometheus metric 20 seconds apart:

```
t0:  strimzi_reconciliations_total{kind="Kafka",namespace="kafka",selector=""} 970.0
t20: strimzi_reconciliations_total{kind="Kafka",namespace="kafka",selector=""} 984.0
```

That is roughly one Kafka reconciliation every 1.4 seconds, continuously, on a single cluster that is not changing.

## Only one manager writes the status

I checked whether a second controller was fighting over the status via server-side apply. It is not. There is a single manager owning the status subresource, the Cluster Operator itself:

```
$ kubectl get kafka kafka-cluster -n kafka --show-managed-fields -o json | jq '[.metadata.managedFields[] | {manager, operation, subresource, time}]'
[
  {
    "manager": "strimzi-cluster-operator",
    "operation": "Update",
    "subresource": "status",
    "time": "2026-04-29T08:25:49Z"
  },
  {
    "manager": "kubectl-annotate",
    "operation": "Update",
    "subresource": null,
    "time": "2026-06-29T05:59:31Z"
  },
  {
    "manager": "kubectl-client-side-apply",
    "operation": "Update",
    "subresource": null,
    "time": "2026-08-20T19:26:41Z"
  },
  {
    "manager": "strimzi-cluster-operator",
    "operation": "Update",
    "subresource": "status",
    "time": "2026-08-21T01:09:27Z"
  }
]
```

The only manager touching `subresource: status` is `strimzi-cluster-operator`. The `kubectl-annotate` and `kubectl-client-side-apply` entries are on the main resource (spec/metadata) from earlier manual edits, not on the status, and they are static. So the operator is reacting to its own status write, not to another actor.

## Things I ruled out

I chased a few other explanations before landing on the timestamp, in case it saves anyone time:

- **CPU throttling.** `cpu.stat` in the operator's cgroup shows `nr_throttled 0` and `nr_periods 0`, so the container is not being CFS-throttled. The high CPU is real work, not a measurement artifact.
- **GC pressure.** `jvm_gc_overhead` is around 0.0015 and heap old gen sits at roughly 18% of max, so it is not GC thrashing.
- **Orphaned connectors.** I had a separate KafkaConnect at `replicas: 0` with live KafkaConnectors, which produced a different loop (`has 0 replicas`). I removed those and that loop stopped, but the Kafka reconciliation loop described here continued independently.
- **metadataVersion mismatch.** `spec.kafka.metadataVersion` and `status.kafkaMetadataVersion` both read `4.3-IV0`, so it is not a spec/status divergence there.
- **CA renewal window.** The cluster uses external CAs (`generateCertificateAuthority: false`) that I rotate on a short cycle, so the CA certs are inside the default 30-day `renewalDays` window. I suspected the CaReconciler was re-evaluating a renewal it cannot perform, but setting explicit `renewalDays`/`validityDays` on both `clusterCa` and `clientsCa` did not change the behavior, so I do not think the renewal window is the cause.

## Environment

- Strimzi Cluster Operator: 1.2.0
- Kafka: 4.3.1 (image `quay.io/strimzi/kafka:1.2.0-kafka-4.3.1`), KRaft, single-node dual-role
- Installation: Helm chart 1.2.0
- CAs: external, `generateCertificateAuthority: false` for both cluster and clients CA
- Kubernetes: 1.36.4

### Steps to reproduce

This started immediately after the operator upgrade, so the reproduction as I hit it was:

1. Running cluster on Cluster Operator 1.1.0 with Kafka 4.2.1, KRaft, single-node dual-role, external CAs (`generateCertificateAuthority: false`).
2. Upgrade the operator to 1.2.0 (applied the 1.2.0 CRDs, then the Helm upgrade).
3. Upgrade Kafka 4.2.1 -> 4.3.1 in two steps (`spec.kafka.version` to 4.3.1, then `metadataVersion` to 4.3-IV0).
4. Watch the Cluster Operator reconcile the Kafka resource once per second from then on.

I have not tried to reproduce it from a clean install on 1.2.0, so I cannot yet say whether the external-CA setup or the KRaft single-node topology is required to trigger it, or whether it happens on any 1.2.0 cluster. Happy to test a specific configuration if that helps narrow it down.

### Expected behavior

When a reconciliation produces no change to the `Ready` condition's status, `lastTransitionTime` should be preserved from the existing condition rather than regenerated. With the timestamp stable, the status write would be a no-op, the watch would not fire a MODIFIED event, and the cluster would fall back to the normal periodic reconciliation instead of looping.

### Strimzi version

1.2.0

### Kubernetes version

1.36.4

### Installation method

Helm chart

### Infrastructure

KVM

### Configuration files and logs
 
Full YAMLs and operator logs collected with `tools/report.sh` are attached as a ZIP (`report.sh --namespace kafka --cluster kafka-cluster --connect kafka-connect-postgres-mongodb`).
 
The key pieces are also inline above:
 
- The operator log showing the `(watch)` loop (`Status ... has been updated` -> `... was MODIFIED` -> next reconciliation) is under "It is triggered by the watch, not the timer".
- The `.status` diff showing only `lastTransitionTime` moving is under "What triggers the loop".
- The `managedFields` output showing a single status manager is under "Only one manager writes the status".
The Kafka resource is deployed with external CAs. The relevant part of the spec:
 
```yaml
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  clusterCa:
    generateCertificateAuthority: false
    generateSecretOwnerReference: false
  clientsCa:
    generateCertificateAuthority: false
    generateSecretOwnerReference: false
  kafka:
    version: "4.3.1"
    metadataVersion: "4.3-IV0"
  # single-node dual-role KafkaNodePool, KRaft
```
 
(Redact any credentials in the KafkaConnector configs and the Secrets before attaching the ZIP, since the connectors carry the MongoDB Atlas and PostgreSQL connection details.)

### Additional context

The cluster stays `Ready=True` and the data pipeline is unaffected throughout, so the practical impact is the operator sitting at 550-800m CPU permanently instead of idling. On 1.1.0 the exact same cluster did not do this. If it would help, I can capture a full DEBUG-level reconciliation trace for a single cycle, or the complete `.status` object, just let me know what is most useful.

**Comment by scholzj** [comment]
The DEBUG log level will show you the diffs. But my guess is that you did not installed the CRDs for 1.2.0? (Keep in mind that when you use Helm, you have to do that manually, Helm with not do it for you - this is a Helm thing, not Strimzi thing)

**Comment by mhorcajada** [comment]
You were right, thank you. The CRDs were still the ones from my original install back in March, they never got updated when I moved to 1.1.0 or 1.2.0. creationTimestamp on all ten was 2026-03-24.

I apply the operator through Flux, and Flux was only updating the operator Deployment, not the CRDs, so they just kept lagging behind. That is the Helm/GitOps side of it you mentioned.

Applying strimzi-crds-1.2.0.yaml fixed it straight away. The reconciliation loop stopped, the operator dropped from ~600m back down to 3m CPU, and the .status is stable now, the lastTransitionTime no longer moves. No restart of the broker or anything else was needed, the pipeline kept running through it.

So this was on my side, not a bug. Sorry for the noise, and thanks for spotting it so fast. Closing.

**Comment by scholzj** [comment]
@mhorcajada No worries. Glad we solved it quickly and that it wasn't anything serious.
