### ISSUE TITLE
[Bug]: After Upgrade strimzi-kafka-operator from 0.44.0 (Kafka 3.8.0) to 0.45.0 (Kafka 3.8.0) some KafkaConnector not starting anymore

### ISSUE THREAD

**Issue by cyrmue** [strimzi/strimzi-kafka-operator#11057]
### Bug Description

After upgrading strimzi-kafka-operator from 0.44.0 to 0.45.0 some of the KafkaConnector (Tasks) not starting anymore, if we revert back to 0.44.0 everything is working. The build process for the image is working fine. But when the Connect Pod is starting, the Tasks are not starting anymore.

`kubectl describe kafkaconnector kafka-connect-kb-elastic-sink-xxx
...
  Connector Status:
    Connector:
      State:      RUNNING
      worker_id:  kafka-connect-kb-connect-0.kafka-connect-kb-connect.infra-kafka-dev.svc:8083
    Name:         kafka-connect-kb-elastic-sink-xxx
    Tasks:
      Id:     0
      State:  FAILED
      Trace:  java.lang.NoSuchMethodError: 'void org.apache.kafka.common.security.ssl.SslFactory.<init>(org.apache.kafka.common.network.Mode, java.lang.String, boolean)'
              at io.confluent.connect.elasticsearch.ConfigCallbackHandler.sslContext(ConfigCallbackHandler.java:261)
              at io.confluent.connect.elasticsearch.ConfigCallbackHandler.createConnectionManager(ConfigCallbackHandler.java:172)
              at io.confluent.connect.elasticsearch.ConfigCallbackHandler.customizeHttpClient(ConfigCallbackHandler.java:95)
              at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:320)
              at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
              at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:283)
              at io.confluent.connect.elasticsearch.ElasticsearchClient.<init>(ElasticsearchClient.java:144)
              at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:82)
              at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:54)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:324)
              at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:176)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:281)
              at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:238)
              at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
              at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
              at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
              at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
              at java.base/java.lang.Thread.run(Thread.java:840)
`

### Expected behavior

The tasks should start the same as with the old version

### Strimzi version

0.45.0

### Kubernetes version

Kubernetes 1.31.1

### Installation method

Helm

### Configuration files and logs

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ include "kafkaconnect.name" . }}-elastic-sink-xxx
  labels:
    strimzi.io/cluster:  {{ include "kafkaconnect.name" . }}
  annotations:
    support-ldap-groups: '["g_kaf_kb"]'
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  tasksMax: 4
  state: {{ .Values.connector.state }}
  config:
    connection.url: "https://elasticsearch-xxx-http.kern-xxx-{{ .Values.global.environment }}:9200"
    connection.username: "elastic"
    connection.password: ${secrets:kern-partner-partnersuche-{{ .Values.global.environment }}/elasticsearch-xxx:elastic}
    topics: "priv.partner.evt.xxx.0"
    batch.size: 2000
    elastic.security.protocol: "SSL"
    elastic.https.ssl.truststore.type: "PEM"
    elastic.https.ssl.truststore.certificates: ${secrets:kern-partner-partnersuche-{{ .Values.global.environment }}/elasticsearch-partnersuche-es-http-certs-public:tls.crt}
    #using own consumer group
    consumer.override.group.id: {{ .Values.connect.kafkaUser }}.xxx
    # flush.synchronously: true needed for transforms... => change Index-Name (Default TopicName)
    flush.synchronously: true
    transforms: "changeIndexname"
    transforms.changeIndexname.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.changeIndexname.regex: "(.*)"
    transforms.changeIndexname.replacement: "partnersuche-person-adressen"
    #using message key for _id in ES
    #key.ignore: true
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    schema.ignore: true
    #max.retries: 5
    #retry.backoff.ms: 100
    connection.compression: false
    max.connection.idle.time.ms: 60000
    connection.timeout.ms: 1000
    read.timeout.ms: 3000
    behavior.on.null.values: DELETE
    behavior.on.malformed.documents: WARN
    errors.tolerance: "all"
    errors.deadletterqueue.topic.name: {{ .Values.elastic.deadletter.topic }}
    errors.deadletterqueue.context.headers.enable: true
    errors.deadletterqueue.topic.replication.factor: -1

**Comment by scholzj** [comment]
Why do you think this is a Strimzi bug? Seems either like some issue with the connector or that you are missing some dependencies.

Also, please:
* Make sure the configurations and logs you share are properly formatted to make them readable.
* Share full logs from the Pod startup
* Share the actual resources from the Kubernetes cluster and not some unrendered templates where it is not clear to anyone else how the actual configuration looks like

**Comment by cyrmue** [comment]
As everything was working fine with Strimzi 0.44.0 and we just moved to 0.45.0 (no changes in Kafka Version other configs and so on). That was the reason to open it as bug. I couldn't find a any change in this project for any relevant changes. I was just hoping, some others have also issue. you could also remove the "bug" tag on it.

**Comment by scholzj** [comment]
Well, if you think it is caused by Strimzi, you should do the stuff asked for above. But in general, Strimzi only creates the connector in the Kafka Connect REST API. The rest is between between the connector and Kafka. It could for example be that the connector is incompatible with a newer Kafka version. There is a similar (but not exactly the same) issue with another connector in another thread.

**Comment by ppatierno** [comment]
AFAICS from Kafka 3.8.x to Kafka 3.9.x, the project renamed the `org.apache.kafka.common.network.Mode` class to `org.apache.kafka.common.network.ConnectionMode` (https://github.com/apache/kafka/commit/6897b06b03917847f599c9e30897228233eee78a). 
See also that in the `SslFactory` constructor in 3.9.0 https://github.com/apache/kafka/commit/6897b06b03917847f599c9e30897228233eee78a and in 3.8.0 https://github.com/apache/kafka/blob/3.8.0/clients/src/main/java/org/apache/kafka/common/security/ssl/SslFactory.java#L77

From your log, it seems that the Confluent elasticsearch connector still refers to the `SslFactory` constructor getting the `Mode` class here https://github.com/confluentinc/kafka-connect-elasticsearch/blob/v14.1.2/src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java#L261.

When you upgraded to Strimzi 0.45.0 did you stay on Kafka 3.8 or upgraded to Kafka 3.9 as well?
In any case it's not a Strimzi bug. There is nothing we can do about it.

**Comment by ppatierno** [comment]
Also adding that this confluent elasticsearch connector is using a Kafka version masked behind some Confluent version.
I don't know which version of the connector you are using but, looking at the master pom here https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/pom.xml you can see it uses a `kafka.version` property which is declared in a parent pom here https://github.com/confluentinc/common/blob/master/pom.xml#L57.
Look for your exact version but anyway you will get a Kafka Confluent and not a Kafka upstream version, 3.8.x or 3.9.x so I don't know on which original version it's built on.

**Comment by scholzj** [comment]
@ppatierno Yeah, that is why the logs are important -> the title suggests both versions use Kafka 3.8. But the issue would point to Kafka 3.9 being used after the upgrade.

**Comment by cyrmue** [comment]
And thanks for your really create job!!!

**Comment by cyrmue** [comment]
Our problem was that we didn't specified (set) KafkaConnectSpec.version to (3.8.0) and therefore the change of the strimzi-kafka-operator changed automatically in the build for kafkaconnect to kafka 3.9.0 (libs). (our fault in the procedure)

**Comment by scholzj** [comment]
@cyrmue Thanks for reporting back the cause. Just keep in mind that you should probably make sure the maintainers of the connector are aware of the issue and fix it, as you might need to upgrade to 3.9 or 4.0 sooner or later.
